#!/usr/bin/env python3
"""
生成自定义调色 LUT 文件
参数: Lift=+0.05, Gamma=+3%, Contrast=+10%, Saturation=+15%
"""
import math

def generate_1d_curve(slope=1.0, offset=0.0, power=1.0):
    """生成 1D 曲线 LUT (33点)"""
    lut = []
    for i in range(33):
        t = i / 32.0
        # Lift/Gamma/Gain 风格的转换
        val = offset + slope * math.pow(max(0, t), power)
        lut.append(max(0.0, min(1.0, val)))
    return lut

def generate_3d_lut(size=33):
    """
    生成 3D LUT 并应用:
    - Lift (暗部): +0.05 (整体上移)
    - Gamma (中间调): 1.03 (略微提亮)
    - Contrast: 1.1 (增加对比度)
    - Saturation: 1.15 (增加饱和度)
    """
    # 先算 1D 变换
    slope = 1.1  # contrast
    offset = 0.05  # lift/offset
    power = 1.03  # gamma
    
    lut_1d = generate_1d_curve(slope, offset, power)
    
    lines = []
    lines.append(f"# Generated by DaVinci EAL")
    lines.append(f"# Title: Custom Color Grade")
    lines.append(f"# LUT_3D_SIZE {size}")
    lines.append("")
    
    # 生成 3D LUT
    for b in range(size):
        for g in range(size):
            for r in range(size):
                # 归一化到 [0, 1]
                tr = r / (size - 1)
                tg = g / (size - 1)
                tb = b / (size - 1)
                
                # 应用 1D 曲线
                rr = lut_1d[min(int(tr * 32 + 0.5), 32)]
                gg = lut_1d[min(int(tg * 32 + 0.5), 32)]
                bb = lut_1d[min(int(tb * 32 + 0.5), 32)]
                
                # 应用饱和度
                avg = (rr + gg + bb) / 3.0
                sat = 1.15
                rr = avg + sat * (rr - avg)
                gg = avg + sat * (gg - avg)
                bb = avg + sat * (bb - avg)
                
                # 限制范围
                rr = max(0.0, min(1.0, rr))
                gg = max(0.0, min(1.0, gg))
                bb = max(0.0, min(1.0, bb))
                
                lines.append(f"{rr:.6f} {gg:.6f} {bb:.6f}")
    
    return "\n".join(lines)

lut_content = generate_3d_lut(33)
output_path = r"C:\Users\123\.openclaw\workspace\skills\davinci-eal\EAL_Grade.cube"
with open(output_path, "w") as f:
    f.write(lut_content)

print(f"LUT saved to: {output_path}")
print(f"File size: {len(lut_content)} bytes")

# 验证
with open(output_path) as f:
    lines = f.readlines()
print(f"Total lines: {len(lines)}")
print(f"First 10 lines:")
for l in lines[:10]:
    print("  ", l.rstrip())
